name: smartlink
description: SmartLink - connect APIs and smart devices quickly.
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.2
  fl_chart: ^0.69.0   # Rich charts

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
